[package]
name = "jc-nes"
version = "0.1.0"
authors = ["João Dias Conde Azevedo <joaodiasconde@gmail.com>"]
edition = "2018"

[dependencies]
sdl2 = { version = "0.34.3", features = ["bundled", "static-link"] }
bitflags = "1.2.1"
