[package]
name = "jc-nes"
version = "0.1.0"
authors = ["João Dias Conde Azevedo <joaodiasconde@gmail.com>"]
edition = "2018"

[dependencies]
bitflags = "1.2.1"
sdl2 = { version = "0.34.2", features = ["bundled", "static-link"] }

[profile.release]
debug = false
lto = true
opt-level = 3
