[package]
name = "jc-nes"
version = "0.1.0"
authors = ["João Dias Conde Azevedo <joaodiasconde@gmail.com>"]
edition = "2018"

[dependencies.bitflags]
version = "1.2.1"

[dependencies.wasm-bindgen]
version = "0.2"
default-features = false

[profile.release]
debug = false
lto = true
opt-level = 3
