name: Main Workflow
on: [push]
env:
  LIB: jc-nes
  DESKTOP: jc-nes-desktop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - run: rustup component add rustfmt
        - run: rustup component add clippy
        - run: cd ${{ env.LIB }} && cargo fmt --all -- --check
        - run: cd ${{ env.LIB }} && cargo clippy -- -D clippy::all
        - run: cd ${{ env.LIB }} && cargo build --release
        - run: cd ${{ env.DESKTOP }} && cargo fmt --all -- --check
        - run: cd ${{ env.DESKTOP }} && cargo clippy -- -D clippy::all
        - run: cd ${{ env.DESKTOP }} && cargo build --release
